--1.
SELECT EMP_ID , EMP_NAME , PHONE , TO_CHAR(HIRE_DATE, 'YY/MM/DD')
FROM EMPLOYEE 
WHERE EMP_NAME !='전지연'
AND DEPT_CODE = (SELECT DEPT_CODE FROM EMPLOYEE WHERE EMP_NAME = '전지연');


--2.
SELECT *
FROM (SELECT EMP_ID ,EMP_NAME ,PHONE ,SALARY ,JOB_NAME
	FROM EMPLOYEE
	JOIN JOB USING(JOB_CODE)
	WHERE EXTRACT(YEAR FROM HIRE_DATE)>2000
	ORDER BY SALARY DESC)
WHERE ROWNUM =1;

--3.
SELECT EMP_ID , EMP_NAME, DEPT_CODE , JOB_CODE , DEPT_TITLE, JOB_NAME
FROM EMPLOYEE 
JOIN JOB USING(JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE=DEPT_ID)
WHERE EMP_NAME !='노옹철'
AND (DEPT_CODE,JOB_CODE)  = (SELECT DEPT_CODE,JOB_CODE FROM EMPLOYEE WHERE EMP_NAME = '노옹철');

--4.
SELECT EMP_ID, EMP_NAME, DEPT_CODE, JOB_CODE, TO_CHAR(HIRE_DATE, 'YY/MM/DD')
FROM EMPLOYEE 
WHERE (DEPT_CODE,JOB_CODE) = (SELECT DEPT_CODE,JOB_CODE FROM EMPLOYEE WHERE EXTRACT(YEAR FROM HIRE_DATE)=2000);

--5.
SELECT EMP_ID, EMP_NAME, DEPT_CODE, MANAGER_ID, EMP_NO, TO_CHAR(HIRE_DATE, 'YY/MM/DD')
FROM EMPLOYEE
WHERE (DEPT_CODE, MANAGER_ID) = (SELECT DEPT_CODE, MANAGER_ID FROM EMPLOYEE
								WHERE SUBSTR(EMP_NO,1,2) = 77 AND SUBSTR(EMP_NO,8,1) = 2);

--6.
SELECT EMP_ID, EMP_NAME , NVL(DEPT_TITLE,'소속없음'), JOB_NAME ,TO_CHAR(HIRE_DATE, 'YY/MM/DD')
FROM EMPLOYEE MAIN
JOIN JOB USING(JOB_CODE)
LEFT JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
WHERE HIRE_DATE = (SELECT MIN(HIRE_DATE)
					FROM EMPLOYEE SUB
					WHERE (ENT_YN = 'N' AND NVL(SUB.DEPT_CODE,'1') = NVL(MAIN.DEPT_CODE,'1')))
ORDER BY HIRE_DATE;
							
							
--7.
SELECT EMP_ID ,EMP_NAME ,JOB_NAME, FLOOR(MONTHS_BETWEEN(SYSDATE,TO_DATE('19'||SUBSTR(EMP_NO,1,6)))/12) 나이,
		TO_CHAR((SALARY+(SALARY*NVL(BONUS,0)))*12,'L999,999,999') 보너스포함연봉
FROM EMPLOYEE MAIN
JOIN JOB J ON (J.JOB_CODE = MAIN.JOB_CODE)
WHERE EMP_NO = (SELECT MAX(EMP_NO)
				FROM EMPLOYEE SUB
				WHERE MAIN.JOB_CODE = SUB.JOB_CODE)
ORDER BY 나이 DESC;






