--1.
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD')  입학년도 
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE ;

--2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___'; 

--3.
SELECT PROFESSOR_NAME 교수이름, FLOOR(MONTHS_BETWEEN(TO_DATE(SYSDATE) , TO_DATE('19'||SUBSTR(PROFESSOR_SSN,1,6),'RRRRMMDD'))/12) 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1
ORDER BY 나이;

--4.
SELECT SUBSTR(PROFESSOR_NAME,2) 이름
FROM TB_PROFESSOR ;

--5.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE 19 < (EXTRACT(YEAR FROM ENTRANCE_DATE) - (19 ||SUBSTR(STUDENT_SSN,1,2)));

--6.
SELECT TO_CHAR (TO_DATE('2020-12-25'),'DAY') "2020년 크리스마스 요일" FROM DUAL;

--7.
SELECT TO_CHAR(TO_DATE('99/10/11','YY/MM/DD'),'YYYY"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('49/10/11','YY/MM/DD'),'YYYY"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('99/10/11','RR/MM/DD'),'RRRR"년" MM"월" DD"일"') FROM DUAL;
SELECT TO_CHAR(TO_DATE('49/10/11','RR/MM/DD'),'RRRR"년" MM"월" DD"일"') FROM DUAL;

--8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

--9.
SELECT ROUND(AVG(POINT),1) 평점
FROM TB_STUDENT 
NATURAL JOIN TB_GRADE 
WHERE STUDENT_NO = 'A517178';

--10.
SELECT DEPARTMENT_NO 학과번호, COUNT(STUDENT_NO) "학생수(명)"
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

--11.
SELECT COUNT(*)
FROM TB_STUDENT 
WHERE COACH_PROFESSOR_NO IS NULL;

--12.
SELECT SUBSTR(TERM_NO,1,4) 년도, ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_STUDENT 
NATURAL JOIN TB_GRADE 
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY SUBSTR(TERM_NO,1,4);

--13.
SELECT DEPARTMENT_NO 학과코드명,SUM(
	CASE WHEN (ABSENCE_YN = 'Y') THEN 1 
	ELSE 0 END) "휴학생 수"
FROM TB_STUDENT 
GROUP BY DEPARTMENT_NO 
ORDER BY DEPARTMENT_NO ;

--14.
SELECT E1.STUDENT_NAME 동일이름, COUNT(*) "동명인 수"
FROM TB_STUDENT E1
JOIN TB_STUDENT E2 ON(E1.STUDENT_NAME = E2.STUDENT_NAME)
WHERE E1.STUDENT_NO != E2.STUDENT_NO
GROUP BY E1.STUDENT_NAME
ORDER BY E1.STUDENT_NAME ;

--15.
SELECT SUBSTR(TERM_NO,1,4) 년도, SUBSTR(TERM_NO,5,2) 학기, ROUND(AVG(POINT),1) 평점
FROM TB_GRADE 
NATURAL JOIN TB_STUDENT 
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4) ,SUBSTR(TERM_NO,5,2))
ORDER BY SUBSTR(TERM_NO,1,4);



