--1.
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT 
ORDER BY STUDENT_NAME ;

--2.
SELECT STUDENT_NAME ,STUDENT_SSN 
FROM TB_STUDENT 
WHERE ABSENCE_YN ='Y'
ORDER BY STUDENT_SSN DESC;

--3.
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT 
WHERE STUDENT_ADDRESS LIKE '강원도%' OR STUDENT_ADDRESS LIKE '경기도%'
AND SUBSTR(STUDENT_NO,1,1)='9'
ORDER BY STUDENT_NAME;

--4.
SELECT PROFESSOR_NAME ,PROFESSOR_SSN 
FROM TB_PROFESSOR P 
JOIN TB_DEPARTMENT D ON(P.DEPARTMENT_NO = D.DEPARTMENT_NO) 
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN ;

--5.
SELECT S.STUDENT_NO , TO_CHAR(G.POINT, 'FM9.00') 학점
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE G.TERM_NO = '200402' AND G.CLASS_NO ='C3118100'
ORDER BY POINT DESC; 

--6.
SELECT S.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
ORDER BY STUDENT_NAME ;

--7.
SELECT CLASS_NAME , DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO );

--8.
SELECT C.CLASS_NAME ,P.PROFESSOR_NAME
FROM TB_PROFESSOR P
JOIN TB_CLASS_PROFESSOR CP ON (P.PROFESSOR_NO = CP.PROFESSOR_NO)
JOIN TB_CLASS C ON(CP.CLASS_NO = C.CLASS_NO);

--9.
SELECT C.CLASS_NAME ,P.PROFESSOR_NAME
FROM TB_PROFESSOR P
JOIN TB_CLASS_PROFESSOR CP ON (P.PROFESSOR_NO = CP.PROFESSOR_NO)
JOIN TB_CLASS C ON(CP.CLASS_NO = C.CLASS_NO)
JOIN TB_DEPARTMENT D ON(C.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';

--10.
SELECT S.STUDENT_NO 학번, S.STUDENT_NAME "학생 이름", ROUND(AVG(G.POINT),1) "전체 평점"
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO )
WHERE S.DEPARTMENT_NO = (SELECT DEPARTMENT_NO FROM TB_DEPARTMENT
					WHERE DEPARTMENT_NAME = '음악학과')
GROUP BY S.STUDENT_NO, S.STUDENT_NAME
ORDER BY S.STUDENT_NO ;

--11.
SELECT DISTINCT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름,
		(SELECT PROFESSOR_NAME FROM TB_PROFESSOR WHERE PROFESSOR_NO =
		(SELECT COACH_PROFESSOR_NO FROM TB_STUDENT WHERE STUDENT_NO = 'A313047'))
		지도교수이름
FROM TB_STUDENT 
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE STUDENT_NO = 'A313047';

--12.
SELECT S.STUDENT_NAME , G.TERM_NO 
FROM TB_STUDENT S
LEFT JOIN TB_GRADE G ON(S.STUDENT_NO = G.STUDENT_NO )
WHERE G.CLASS_NO = (SELECT CLASS_NO FROM TB_CLASS WHERE CLASS_NAME ='인간관계론')
AND SUBSTR(TERM_NO,1,4) = '2007'
ORDER BY S.STUDENT_NAME;


--13.
SELECT C.CLASS_NAME, DEPARTMENT_NAME 
FROM TB_CLASS_PROFESSOR CP
FULL JOIN TB_CLASS C ON(CP.CLASS_NO = C.CLASS_NO)
FULL JOIN TB_DEPARTMENT D ON(C.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE CATEGORY = '예체능' AND PROFESSOR_NO IS NULL;

--14.
SELECT S.STUDENT_NAME 학생이름 , NVL(P.PROFESSOR_NAME,'지도교수 미지정') 지도교수
FROM TB_STUDENT S
LEFT JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO=D.DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;

--15.
SELECT S.STUDENT_NO 학번, S.STUDENT_NAME 이름, D.DEPARTMENT_NAME "학과 이름", AVG(POINT) 평점
FROM TB_STUDENT S
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO=D.DEPARTMENT_NO)
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE S.ABSENCE_YN = 'N'
GROUP BY S.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0 
ORDER BY 학번;

--16.
SELECT C.CLASS_NO, C.CLASS_NAME, TRUNC(AVG(POINT),8)
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO) 
JOIN TB_GRADE G ON (C.CLASS_NO=G.CLASS_NO)
WHERE D.DEPARTMENT_NAME = '환경조경학과' AND C.CLASS_TYPE = '전공선택'
GROUP BY C.CLASS_NO, C.CLASS_NAME
ORDER BY C.CLASS_NO;

--17.
SELECT STUDENT_NAME , STUDENT_ADDRESS 
FROM TB_STUDENT
WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO  FROM TB_STUDENT WHERE STUDENT_NAME ='최경희');

--18.
SELECT STUDENT_NO , STUDENT_NAME 
FROM (SELECT D.DEPARTMENT_NAME, S.STUDENT_NO, S.STUDENT_NAME , AVG(G.POINT)
		FROM TB_STUDENT S
		JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO=D.DEPARTMENT_NO)
		JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO) 
		WHERE D.DEPARTMENT_NAME ='국어국문학과'
		GROUP BY D.DEPARTMENT_NAME, S.STUDENT_NO, S.STUDENT_NAME ,G.STUDENT_NO
		ORDER BY AVG(G.POINT) DESC)
WHERE ROWNUM = 1;

--19.
SELECT DISTINCT D.DEPARTMENT_NAME "계열 학과명" , ROUND(AVG(G.POINT),1) 전공평점
FROM TB_DEPARTMENT D
LEFT JOIN TB_STUDENT S ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
LEFT JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
WHERE CATEGORY = (SELECT CATEGORY FROM TB_DEPARTMENT WHERE DEPARTMENT_NAME = '환경조경학과')
GROUP BY D.DEPARTMENT_NAME
ORDER BY D.DEPARTMENT_NAME;
