--1.
SELECT STUDENT_NAME "학생 이름", STUDENT_ADDRESS 주소지
FROM TB_STUDENT 
ORDER BY STUDENT_NAME ;

--2.
SELECT STUDENT_NAME ,STUDENT_SSN 
FROM TB_STUDENT 
WHERE ABSENCE_YN ='Y'
ORDER BY STUDENT_SSN DESC;

--3.
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT 
WHERE STUDENT_ADDRESS LIKE '강원도%' OR STUDENT_ADDRESS LIKE '경기도%'
AND SUBSTR(STUDENT_NO,1,1)='9';

--4.
SELECT PROFESSOR_NAME ,PROFESSOR_SSN 
FROM TB_PROFESSOR 
NATURAL JOIN TB_DEPARTMENT 
WHERE DEPARTMENT_NAME = '법학과'
ORDER BY PROFESSOR_SSN ;

--5.

--6.
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT 
NATURAL JOIN TB_DEPARTMENT
ORDER BY STUDENT_NAME ;

--7.
SELECT CLASS_NAME , DEPARTMENT_NAME
FROM TB_CLASS 
NATURAL JOIN TB_DEPARTMENT ;

--8.
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_CLASS C
RIGHT JOIN TB_PROFESSOR P ON (C.DEPARTMENT_NO = P.DEPARTMENT_NO);
--9.



